[package]
name = "mvm"
version = "0.1.0"
authors = ["Miroslav Krýsl <mkrysl@protonmail.com>"]
edition = "2018"

[dependencies]
#nom = "6.0.0-alpha1"
pom = "3.1.0"
#log = "0.4.8"
#combine = "4.2.1"
thiserror = "1.0.20"
regex = "1.3.7"
itertools = "0.9.0"
lazy_static = "1.4.0"
derive_more = "0.99.8"